name:                pretty-terminal
version:             0.1.0.0
github:              "loganmac/pretty-terminal"
license:             BSD3
author:              "Logan McPhail"
maintainer:          "logan.airnomad@gmail.com"
copyright:           "2018 Logan McPhail"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Styling and coloring terminal output with ANSI escape sequences.
category:            Terminal

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/loganmac/pretty-terminal#readme>

dependencies:
- base >= 4.7 && < 5
- text

library:
  source-dirs: src

ghc-options:
  - -Wall
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wtabs

executables:
  pretty-terminal-example:
    main:                Main.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pretty-terminal
